### ISSUE TITLE
Rotating only keeps working in one axis

### ISSUE THREAD

**Issue by mklomp** [X-Ryl669/grav-plugin-viewer3d#2]
Hi, thanks for the nice plugin! I ran into a small issue.

When rotating my object by moving my mouse in a horizontal direction the model moves clockwise or counterclockwise. When doing the the same in the vertical direction the model will not continue to turn but can only be turned 180 degrees.

**Comment by X-Ryl669** [comment]
I wonder if it's linked with scroll being enabled in that case. Can you try on a page without a scroll bar?
Does it happen [here](https://blog.cyril.by/fr/documentation/3d%20models/vga-connector) for you and if not, can you share an URL where I can have a look ?
Thanks!

**Comment by mklomp** [comment]
Is also happens on the link you provided. Also checked with Chrome, Firefox and Edge without any effect. Unfortunately I do not have a URL, but as mentioned this also happens on the link you provided. Not sure though how to explain the situation in a better way.....

**Comment by X-Ryl669** [comment]
I'll try to explain what I've understood:
1. In the provided link above, you click on the model (with a mouse ? a touchpad ? a touchscreen ?) and move your pointer horizontally.
2. The model rotate on the Z axis accordingly (so you can adjust the Z angle very precisely)
3. If you move your pointer vertically, 
4. The model does not rotate on the X axis smoothly (only by large step of 180 degrees), right ?

I've tried here with a touchpad, a mouse and a touchscreen (the former running Firefox then Brave on linux and the latter on an Android phone), and it's working for me as expected (that is: not like 4, I can rotate smoothly on both Z and X axis).

I've checked the code, see [here](https://github.com/X-Ryl669/Online3DViewer/blob/merged/source/viewer/navigation.js) and there is no specific code for Y w.r.t X movement (both are computed the same way). So, the behavior you are describing is hard to understand. Can you describe your setup a bit more ?

**Comment by X-Ryl669** [comment]
Nevermind, I think I've understood what you meant. You meant that you can't rotate more than 90° on Y (respectively less than -90° in Y) ?
In that case, yes, we've a protection to avoid gimbal lock. Look [here](https://github.com/X-Ryl669/Online3DViewer/blob/79d2edb4cd3c3c3e6853d0588769ec775ddcbe91/source/viewer/navigation.js#L516). 

If you need to disable it, you'll need to call:
```
viewerElements[0].viewer.SetFixUpVector(false);
```
in your JS code.

**Comment by mklomp** [comment]
OK, thanks. That indeed was what I encountered and 'fixed' it.
