### ISSUE TITLE
feature req

### ISSUE THREAD

**Issue by ljubomirb** [X-Ryl669/grav-plugin-viewer3d#3]
Hi, I tried viewer and it works very nice, but if you could add option to turn off visual controls  important only for 3d printing, sot that that info box does not even appear to end user. 
That way, admin can load point cloud, for example, and only have rotation box for users to check models. Nothing more, and that is gold and covers most needs for point cloud!

It could be, that to have option to have section cut (or similar "edit" function) would be nice and useful, but it seems to me it works kind of visually ugly for point cloud, at this point, at least in point cloud rooms scan that I tried. That looks like it would require much more work, so I would also prefer not to have it until it's ready. I could be wrong, but that is my impression.

**Comment by X-Ryl669** [comment]
You meant, like when you click the right arrow on the info panel (to collapse it) ?
And to remove the bottom's buttons ?

**Comment by ljubomirb** [comment]
I was thinking - not to show end users (the ones who view web site) any other control other than view box (the one with top/bottom/... to rotate point cloud) object. If such option can be implemented, can it be something similar like "show edges" or something similar that can be turned on or off from admin panel in grav. That way, all web content  creators  who use this plugin for 3d printing can have all they need about mass, density and so... and all other people that will use this plugin (as I would like) for architecture, or possibly landscapes.... can have clear way to show customers point cloud objects. I think you can agree that filament menu has no sense here. (thanks for quick response)

**Comment by X-Ryl669** [comment]
Please pull the latest version and go to the plugin's setting page to disable the features you don't want.
If it's not ok, let me know.

**Comment by ljubomirb** [comment]
Great, it is what I asked for! You can release this version if you want it, people will love it.
