### ISSUE TITLE
[enhance] Zoom

### ISSUE THREAD

**Issue by fampla** [X-Ryl669/grav-plugin-viewer3d#6]
Is it possible to turn off the automatic zoom?
So to have a fixed camera position, as it were, as far as the distance is concerned?
that would be a wonderful addition for me. otherwise I like the plugin very much, thank you very much for that

**Comment by X-Ryl669** [comment]
If you are speaking of the zoom when scrolling the mouse, it's probably possible (by disabling the scroll event) but then what should be the default camera position ?
If you are speaking of the zoom when clicking the navigation cube, that one will be hard to solve as it's computed dynamically based on the model's size.

**Comment by slevin-7** [comment]
the one with the camera position seems to be a translator error.  I mean
zoom with the mouse wheel, the standard size should stay as it is.  Sorry
for the stupid translation, unfortunately I am hardly able to speak English
(even when I practice)

X-Ryl669 ***@***.***> schrieb am Di. 27. Juli 2021 um 20:32:

**Comment by X-Ryl669** [comment]
Please try version 1.0.0, you now have a zoomFactor options in the plugin's option page. Set it to either 0 (disable zooming), or 1 (limit the zoom range so the model does not disappear anymore). 

Let me know if it fixed the issue for you. Thanks!

**Comment by X-Ryl669** [comment]
Closing as it seems fixed.
